# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Transparency Certified
author: The TRACE Team
logo: logo.png
only_build_toc_files: true
exclude_patterns: [venv]

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/transparency-certified/trace-specification
  path_to_book: .
  branch: main

# Add GitHub buttons to your book
html:
  favicon: favicon.ico

sphinx:
  config:
    html_css_files:
      - custom.css
    html_theme_options:
      search_bar_text: "Search..."
      repository_url: https://github.com/transparency-certified/trace-specification
      repository_branch: main
      path_to_docs: docs
      use_issues_button: true
      use_repository_button: true
      use_edit_page_button: true
